package com.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

import com.services.EmailGenerationService;

@RestController
@RequestMapping("/mail")
@CrossOrigin(origins="http://localhost:3000", allowCredentials = "true")
public class EmailGenerationController {
	
	@Autowired
	private EmailGenerationService emailGenerationService;
	
	@PostMapping("/send")
	public String sendAutoGeneratedMail(@RequestParam(value = "file", required = false) MultipartFile[] file, String to, String[] cc, String subject, String body) {
		return emailGenerationService.sendAutoGeneratedMail(file, to, cc, subject, body);
	}

}
